export const referenceNews = [
  {
    "id": "reference-0",
    "date": "2026-10-08",
    "tag": "Publicação",
    "title": "Reveal no SIBGRAPI 2026: exploração de dados urbanos",
    "text": "📢 New paper at SIBGRAPI 2026!\n\nWe're happy to share \"Reveal: A Provenance-Aware System for Multimodal Urban Data Exploration,\" presented at SIBGRAPI 2026.\n\nReveal is a visual analytics system that tackles:\n \n🔎 Multimodal text and image search over a shared CLIP embedding space\n\n 🧩 Set operations to combine and refine urban concepts\n\n 🗺️ Linked views: embedding plots, image galleries, word clouds, and spatial heatmaps\n\n 🧭 An exploration diagram that captures analytical provenance, making each analysis transparent, reproducible, and reusable\n\nIn case studies with an urban planner, Reveal helped expand the Project Sidewalk accessibility taxonomy with 11 new fine-grained categories, covering more than 1,600 newly labeled images. \n\nWe then reused the captured provenance as a \"semantic blueprint\" to replicate the analysis on Chicago street-level imagery.\n\nThis work continues our research line on provenance and scientific data management, applied here to urban visual analytics. It is a collaboration between the UFFeScience Research Group (Daniel de Oliveira, Aline Paes, and Marcos Lage), UIC (Leonardo Ferreira and Fabio Miranda), FGV (Joao Rulff), and UC Berkeley (Maryam Hosseini), and it builds on Leonardo Ferreira's master's work. \n\nCongratulations to all co-authors!\n\n💻 Code and tutorial: https://lnkd.in/dGzXh5V9\n\n#SIBGRAPI2026 #eScience #UFF #Provenance #VisualAnalytics #UrbanComputing #MultimodalData",
    "url": "https://lnkd.in/dGzXh5V9",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-1",
    "date": "2026-09-21",
    "tag": "Publicação",
    "title": "Astronomia e aprendizado federado no CEFET/RJ",
    "text": "On September 17, Prof. Aline Paes (MeLLL@UFF) and Prof. Daniel de Oliveira (UFFeScience Research Group) had the pleasure of giving a talk at CEFET/RJ – Campus Maria da Graça.\n\nThey presented \"Finding the Unexpected: Machine Learning for the Next Generation of Astronomy,\" based on Camila Lopes's PhD research.\n\nModern telescopes produce so much data that analyzing everything with traditional methods is becoming impossible. In the talk, they showed how machine learning can help astronomers find unusual and potentially important objects hidden in huge datasets. Their focus was Federated Learning, an approach that lets different computers train models together without moving all their data to one central location. Using observations from the Dark Energy Survey (DES), they tested how this approach could support future projects like the Legacy Survey of Space and Time (LSST), comparing configurations by speed, reliability, and cost.\n\nHuge thanks to the CEFET/RJ students for their great questions and genuine curiosity. It's inspiring to see young people so interested in our work! \n\nThanks also to Prof. Carlos Eduardo Pantoja and CEFET/RJ for hosting us and welcoming us so warmly.\n\n#MachineLearning #FederatedLearning #Astronomy #DataScience #eScience #UFF #CEFETRJ"
  },
  {
    "id": "reference-2",
    "date": "2026-09-19",
    "tag": "Publicação",
    "title": "CellLens+: nova publicação no BSB 2026",
    "text": "Happy to share that our paper entitled \"A Workflow for Automated Cell-Type Annotation in scRNA-seq Using LLMs and Graph-Based Community Detection\" has been accepted at the Brazilian Symposium on Bioinformatics (BSB 2026)!\n\nThe paper proposes CellLens+, which is a workflow for automated cell-type annotation that brings together graph-based community detection, deterministic molecular inference, and Large Language Models. It detects transcriptionally coherent cell populations, identifies cluster-specific marker genes, and assigns cellular identities through a quantitative scoring framework.\n\nAuthors: Layse Gomes Castro, João Vitor Moraes, and Daniel de Oliveira.\n\nCongratulations, and see you at BSB 2026 in Ribeirão Preto!\n\n#Bioinformatics #SingleCell #scRNAseq #LLM #BSB2026 #UFF"
  },
  {
    "id": "reference-3",
    "date": "2026-09-16",
    "tag": "Publicação",
    "title": "Proveniência de workflows agênticos no APeX Summit",
    "text": "Congratulations to Valesca Moura, who presented the work \"Instrumentation vs. Observability: Provenance Capture Trade-offs in Agentic Workflows\" at the APeX Summit 2026 (Academy, Parsl, Globus Compute).\n\nAs AI agents increasingly take part in scientific workflows, understanding what they did, why, and with which data becomes important for trust and reproducibility. This work looks at a practical question at the heart of this: when capturing provenance in agentic workflows, what do we gain and what do we pay when we instrument the code explicitly versus relying on observability mechanisms?\n\nAnd there's more good news! The paper has been accepted at WISDOM @ IEEE eScience 2026 and will be published soon. \n\nThis was a truly collaborative effort, and we are grateful to work with such a great team: Valesca Moura, Amal Gueroudji, Daniel Rosendo, Ben Clifford, Kyle Chard, Rafael Ferreira da Silva, Daniel de Oliveira and Renan Souza.\n\nLooking forward to what comes next.\n\n🔗 Program and slides: https://lnkd.in/d9c5draW\n\n#eScience #Provenance #AgenticAI #ScientificWorkflows #Observability",
    "url": "https://lnkd.in/d9c5draW",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-4",
    "date": "2026-09-13",
    "tag": "Publicação",
    "title": "PhyloTreeMiner recebe o prêmio de melhor artigo no BreSci",
    "text": "🇧🇷 pt-br\n\nMais uma boa notícia direto do SBBD - Simpósio Brasileiro de Banco de Dados: nosso artigo recebeu o prêmio de Melhor Artigo do XX Brazilian e-Science Workshop (BreSci 2026)! 🏆\n\n\"Mineração de Subárvores Frequentes em Árvores Filogenéticas usando Conjuntos de Itens Frequentes Maximais\" é fruto do trabalho de João Vitor Moraes e Layse Gomes Castro, em parceria com Isabel Rosseti e Daniel de Oliveira, todos do Instituto de Computação UFF.\n\nO ponto de partida é que métodos diferentes produzem árvores filogenéticas distintas a partir dos mesmos dados, e as árvores de consenso — a saída usual — acabam por esconder conflitos topológicos.\n\nO PhyloTreeMiner propõe uma alternativa ao consenso: minerar subárvores frequentes, identificando padrões topológicos recorrentes com base no valor de suporte. Modelamos o problema como mineração de conjuntos de itens frequentes maximais (FPMax), o que reduz o custo computacional, e armazenamos os resultados no Neo4j, permitindo consultas que combinam topologia e metadados.\n\nParabéns, João Vitor e Layse — o prêmio é de vocês! 👏\n\n📄 Artigo: https://lnkd.in/ddQNTUFB\n\n#BreSci2026 #eScience #Filogenia #Bioinformática #DataMining #Neo4j #UFF\n\n🇺🇸 en-us\n\nMore good news from SBBD - Simpósio Brasileiro de Banco de Dados: our paper received the Best Paper Award at the XX Brazilian e-Science Workshop (BreSci 2026)! 🏆\n\n\"Frequent Subtree Mining in Phylogenetic Trees using Maximal Frequent Itemsets\" is the work of João Vitor Moraes and Layse Gomes Castro, together with Isabel Rosseti and Daniel de Oliveira, all from IC/UFF.\n\nDifferent methods produce different phylogenetic trees from the same dataset, and consensus trees—the usual way out—tend to hide topological conflicts and discard relevant evolutionary signal.\n\nPhyloTreeMiner offers an alternative to consensus: mining frequent subtrees to identify recurring topological patterns based on support values. We model the problem as maximal frequent itemset mining (FPMax), which substantially reduces the computational cost, and store the results in Neo4j, enabling queries that combine topology and metadata.\n\nCongratulations, João Vitor and Layse — this award is yours! 👏\n\n📄 Paper: https://lnkd.in/ddQNTUFB\n\n#BreSci2026 #eScience #Phylogenetics #Bioinformatics #DataMining #Neo4j #UFF",
    "url": "https://lnkd.in/ddQNTUFB",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-5",
    "date": "2026-09-13",
    "tag": "Publicação",
    "title": "UFFeScience no SBBD 2026",
    "text": "🇧🇷 pt-br\n\nO UFFeScience Research Group desembarcou em São Carlos para o SBBD - Simpósio Brasileiro de Banco de Dados 2026.\n\nForam apresentados 11 trabalhos, entre artigos completos, artigos curtos, demonstrações e workshops, abrangendo temas como proveniência de workflows agênticos, IA responsável, arquiteturas HTAP, continuum computacional, grafos de conhecimento e bioinformática.\n\nE dois reconhecimentos que coroaram a semana:\n\n 🏆 Melhor Artigo do BreSci 2026\n 🏅 Menção Honrosa de artigos completos no SBBD 2026\n\nMas o número que mais importa não é nenhum desses, é o nosso grupo. Alunos e alunas que transformaram noites de experimento em resultado, coautores e parceiros de outras instituições que somaram conosco, e uma organização impecável do SBBD e do BreSci que fez tudo acontecer.\n\nObrigado a cada um de vocês. 👏\n\nOs artigos estão todos nos comentários. 👇\n\n#SBBD2026 #BreSci2026 #eScience #UFF #BancoDeDados \n\n🇺🇸 en-us\n\nThe UFFeScience Research Group landed in São Carlos for SBBD - Simpósio Brasileiro de Banco de Dados 2026.\n\nEleven works were presented as full papers, short papers, a demo, and workshop contributions, covering topics such as provenance for agentic workflows, responsible AI, HTAP architectures, the computing continuum, knowledge graphs, and bioinformatics.\n\nPlus two recognitions that capped the week:\n\n 🏆 Best Paper Award at BreSci 2026\n 🏅Full Paper Honorable Mention at SBBD 2026\n\nBut the number that matters most isn't any of those, it's our team. The students who turned late-night experiments into results, the co-authors and partners from other institutions who joined us, and the SBBD and BreSci organizers who made it all run flawlessly.\n\nThank you, every one of you 👏\n\nAll the papers are in the comments. 👇\n\n#SBBD2026 #BreSci2026 #eScience #UFF #Databases"
  },
  {
    "id": "reference-6",
    "date": "2026-09-13",
    "tag": "Publicação",
    "title": "ANCHOR recebe menção honrosa no SBBD 2026",
    "text": "🇧🇷 pt-br\n\nNotícia que dá orgulho de compartilhar: o artigo associado a pesquisa de mestrado da Valesca Moura (orientada pelos Profs. Sandro Rama Fiorini e Daniel de Oliveira) recebeu Menção Honrosa no SBBD 2026! \n\nO artigo \"Uma Abordagem Orientada a Dados de Proveniência para Rastreabilidade de Workflows Agênticos\" aborda um problema que cresce com a adoção de agentes de IA: quando um LLM decide as tarefas e as dependências de dados de um workflow, como saber por que o workflow ficou daquele jeito?\n\nA abordagem (ANCHOR) captura a proveniência de workflows agênticos, instrumentando o próprio framework de agentes e representando os dados conforme o padrão W3C PROV. O resultado é a possibilidade de analisar as decisões dos agentes e o impacto delas no workflow gerado, com granularidade superior à dos trabalhos existentes.\n\nParabéns, Valesca! 👏\n\n📄 Artigo: https://lnkd.in/dT2ra9aC\n 💻 Código: https://lnkd.in/dsSVpD-U\n\n#SBBD2026 #Proveniência #WorkflowsAgênticos #AgenticAI #IAResponsável #UFF #eScience\n\n🇺🇸 en-us\n\nProud to share this one: Valesca Moura's master's research (advised by Sandro Fiorini and Daniel de Oliveira) received an Honorable Mention at SBBD 2026! 🏆\n\nThe paper \"A Provenance Data-Oriented Approach for Agentic Workflow Traceability\" tackles a problem that grows with every new AI agent deployment: when an LLM decides tasks and data dependencies, how do we know why a workflow ended up the way it did?\n\nOur approach (ANCHOR) captures provenance from agentic workflows by instrumenting the agent framework itself and representing the data according to the W3C PROV standard. This makes it possible to analyze agents' decisions and their impact on the generated workflow, at a finer granularity than existing approaches offer.\n\nCongratulations, Valesca! 👏\n\n📄 Paper: https://lnkd.in/dT2ra9aC\n 💻 Code: https://lnkd.in/dsSVpD-U\n\n#SBBD2026 #DataProvenance #AgenticWorkflows #AgenticAI #ResponsibleAI #UFF #eScience",
    "url": "https://lnkd.in/dT2ra9aC",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-7",
    "date": "2026-08-22",
    "tag": "Publicação",
    "title": "PROTECTOR: pesquisa sobre rotas de patrulhamento preventivo",
    "text": "🇧🇷 Nova publicação do UFFeScience Research Group!\n\nTemos o prazer de anunciar a publicação do artigo \"Optimizing Preventive Police Patrol Routes in Brazilian Cities Using a GRASP-Based Routing Heuristic\" no Journal of Internet Services and Applications (JISA).\n\nO trabalho aborda o problema de Roteamento de Viaturas Policiais em Grandes Centros Urbanos (RVP-Urb), que busca maximizar a cobertura de áreas críticas de criminalidade respeitando restrições de recursos. A solução proposta, chamada PROTECTOR, é uma heurística baseada no GRASP (Greedy Randomized Adaptive Search Procedure) para gerar rotas de patrulhamento preventivo que aumentam a visibilidade policial em hotspots criminosos.\n\n👥 Autores: Isabel Rosseti, Eduardo Canellas, Wagner Santos, Marcos Lage, Yuri Frota e Daniel de Oliveira.\n\nParabéns a toda a equipe!\n\n🔗 DOI: https://lnkd.in/d2X_giC3\n\n#UFFeScience #UFF #InstitutoDeComputação #JISA #Otimização #GRASP #Metaheurísticas #CidadesInteligentes #CiênciaDeDados #Pesquisa\n\n🇺🇸 New publication from UFFeScience Research Group!\n\nWe're glad to announce the publication of \"Optimizing Preventive Police Patrol Routes in Brazilian Cities Using a GRASP-Based Routing Heuristic\" in the Journal of Internet Services and Applications (JISA).\n\nThe paper tackles the Routing of Police Vehicles in Large Urban Centers (RVP-Urb) problem, which aims at maximizing crime coverage under resource constraints. The proposed solution, PROTECTOR, is a heuristic based on the Greedy Randomized Adaptive Search Procedure (GRASP) that generates preventive patrol routes to enhance police visibility across crime hotspots.\n\n👥 Authors: Isabel Rosseti, Eduardo Canellas, Wagner Santos, Marcos Lage, Yuri Frota, and Daniel de Oliveira.\n\nCongratulations to the whole team! \n\n🔗 DOI: https://lnkd.in/d2X_giC3\n\n#UFFeScience #UFF #JISA #Optimization #GRASP #Metaheuristics #SmartCities #DataScience",
    "url": "https://lnkd.in/d2X_giC3",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-8",
    "date": "2026-08-20",
    "tag": "Publicação",
    "title": "Modelos de linguagem e detecção de capacitismo",
    "text": "🇧🇷 Mais um trabalho em cooperação com o MeLLL@UFF! \n\nNosso artigo \"Beyond Toxicity: Evaluating Language Models for Ableism Detection in Online Social Media\" foi aceito para apresentação no KDMiLe - Knowledge Discovery, Mining and Learning 2026, em Cuiabá.\n\nO artigo investiga como LLMs identificam manifestações de capacitismo em comentários em redes sociais em português brasileiro. Avaliamos diferentes estratégias de prompting e mostramos que contexto adicional pode melhorar o desempenho dos modelos, embora ainda existam desafios importantes na distinção entre capacitismo, críticas ao capacitismo e outros tipos de discurso discriminatório.\n\nParabéns a Annie Amorim, Gabriel Assis, Daniele Pimenta, Débora Pina, Aline Paes e Daniel de Oliveira!\n\nNos vemos no KDMiLe 2026. 🎉\n\n#LLM #AI #NLP #ResponsibleAI #Research #KDMiLe2026\n\n🇺🇸 Another publication in cooperation with MeLLL@UFF!\n\nOur paper, \"Beyond Toxicity: Evaluating Language Models for Ableism Detection in Online Social Media\", has been accepted for presentation at KDMiLe - Knowledge Discovery, Mining and Learning 2026 in Cuiabá, Brazil.\n\nThe study investigates how LLMs identify ableism in Brazilian Portuguese social media comments. We evaluated different prompting strategies and found that additional context can improve model performance, although important challenges remain in distinguishing ableism from criticism of ableism and other forms of discriminatory discourse.\n\nCongratulations to Annie Amorim, Gabriel Assis, Daniele Pimenta, Débora Pina, Aline Paes, and Daniel de Oliveira!\n\nSee you at KDMiLe 2026! 🎉\n\n#LLM #ArtificialIntelligence #NLP #ResponsibleAI #Research #KDMiLe2026"
  },
  {
    "id": "reference-9",
    "date": "2026-08-19",
    "tag": "Publicação",
    "title": "Trabalhos do grupo no SBBD 2026",
    "text": "🎉 UFFeScience Research Group no SBBD 2026!\n\nO UFFeScience Research Group (Instituto de Computação UFF) teve 8 artigos aceitos no XLI SBBD Simpósio Brasileiro de Banco de Dados: 4 completos e 4 curtos! E dois deles concorrem aos prêmios de Melhor Artigo Completo e Melhor Artigo Curto 🏆\n\n📄 ARTIGOS COMPLETOS\n\nUma Abordagem Orientada a Dados de Proveniência para Rastreabilidade de Workflows Agênticos (concorre ao melhor full paper 🏆)\n Valesca Moura, Sandro Rama Fiorini, Daniel de Oliveira\n 🔗 https://lnkd.in/dtjmPKMi\n\nTriptych: Integrando Dados, Código e Publicações para Pesquisa Científica\n Ygor Rolim, Liliane Kunstmann, Débora Pina, Carina F. Dorneles, Marcos Lage, Daniel de Oliveira\n 🔗 https://lnkd.in/dJ4gUtKM\n\nDo Data Warehouse à Narrativa: Uma Arquitetura HTAP para Análise de Dados de Criminalidade\n Ryan Serra, Daniel Ribeiro, Arben Hajrullah S. Tafili, Paulo S. Costa-Jr., João V. Silva-Leite, Rodrigo Salvador Monteiro, Daniel de Oliveira, Marcos Bedo\n 🔗 https://lnkd.in/d9SQtPu2\n\nDefinição de Acordos de Nível de Serviço Personalizados para Treinamento de Modelos via Consultas k-Skyband\n Gustavo Alexandre Santos, Marcos Bedo, Yuri Frota, Daniel de Oliveira\n 🔗 https://lnkd.in/dYF39E-t\n\n📄 ARTIGOS CURTOS\n\nUnderstanding Storage Trade-offs for Containerized Dataflows Across the Computing Continuum (concorre ao melhor short paper 🏆)\n Wesley Ferreira, Luiz Viana, Lucas Natan, Liliane Kunstmann, Daniel de Oliveira\n 🔗 https://lnkd.in/dFHXaWhA\n\nOn Provenance in Model Fusion\n Annie Amorim, João Vitor Moraes, Débora Pina, Aline Paes, Daniel de Oliveira\n 🔗 https://lnkd.in/d6FDfx-i\n\nProvenance Graph Integration in Scientific Machine Learning Multi-workflows\n Débora Pina, Lucas Moreira Dias, Maria Célia Santos Lopes, Daniel de Oliveira, Marta Mattoso\n 🔗 https://lnkd.in/dZBvNywZ\n\nRumo a Duas Décadas de Publicações em Banco de Dados: Uma Análise dos Artigos do JIDM\n Elena Costa Blanco, Josué Santos, Maristela Holanda, Vanessa Braganholo, Marcos Bedo, Daniel de Oliveira\n 🔗 https://lnkd.in/dJdxheEz\n\nUm obrigado especial aos nossos alunos, da iniciação científica ao doutorado: a dedicação de vocês, nas madrugadas de experimento e nas revisões, está em cada página desses artigos. Vocês são o motor deste grupo 💙\n\nParabéns a todas e todos! Nos vemos em São Carlos!\n\n#SBBD2026 #UFF #eScience #BancoDeDados",
    "url": "https://lnkd.in/dtjmPKMi",
    "linkLabel": "Link citado na publicação"
  },
  {
    "id": "reference-10",
    "date": "2026-08-14",
    "tag": "Publicação",
    "title": "Duas indicações a prêmios no SBBD 2026",
    "text": "🇧🇷 (pt-br) 🎉 Ótimas notícias para começar o fim de semana!\n\nÉ com muita alegria que compartilhamos que dois trabalhos com participação do UFFeScience Research Group foram indicados a prêmios no SBBD - Simpósio Brasileiro de Banco de Dados 2026, principal evento da comunidade de bancos de dados no Brasil.\n\n🏅 Indicação a Melhor Artigo Curto\n\n\"Understanding Storage Trade-offs for Containerized Dataflows Across the Computing Continuum\". Autores: Wesley Ferreira (IC/UFF), Luiz Viana (IC/UFF), Lucas Natan (IC/UFF), Liliane Kunstmann (UFRRJ) e Daniel de Oliveira (IC/UFF).\n\n🏅 Indicação a Melhor Artigo Completo (Best Full Paper)\n \n\"Uma Abordagem Orientada a Dados de Proveniência para Rastreabilidade de Workflows Agênticos\". Autores: Valesca Moura (IC/UFF), Sandro Rama Fiorini (Instituto PUC-Behring de Inteligência Artificial) e Daniel de Oliveira (IC/UFF).\n\nParabéns a todos os autores e autoras! Indicações como essas são resultado de meses de dedicação, muitas iterações e de um trabalho verdadeiramente coletivo. \n\nNos vemos no SBBD! \n\n🇺🇸 (en-us) 🎉 Great news to kick off the weekend!\n\nWe're delighted to share that two papers co-authored by the UFFeScience Research Group have been nominated for awards at the Brazilian Symposium on Databases (SBBD) 2026, the leading venue of the Brazilian database community.\n\n🏅 Best Short Paper Nomination\n\n\"Understanding Storage Trade-offs for Containerized Dataflows Across the Computing Continuum\". Authors: Wesley Ferreira (IC/UFF), Luiz Viana (IC/UFF), Lucas Natan (IC/UFF), Liliane Kunstmann (UFRRJ), and Daniel de Oliveira (IC/UFF).\n\n🏅 Best Full Paper Nomination\n\n\"A Provenance-Driven Approach for the Traceability of Agentic Workflows\". Authors: Valesca Moura (IC/UFF), Sandro Rama Fiorini (Instituto PUC-Behring de Inteligência Artificial), and Daniel de Oliveira (IC/UFF).\n\nCongratulations to all the authors! Nominations like these are the result of months of dedication, many iterations, and a truly collective effort.\n\nSee you at SBBD!"
  },
  {
    "id": "reference-11",
    "date": "2026-06-30",
    "tag": "Publicação",
    "title": "Visita ao Barcelona Supercomputing Center",
    "text": "In June, we had the opportunity to visit the Barcelona Supercomputing Center (BSC), where we were warmly hosted by Dr. Débora Pina.\n\nThe visit provided an excellent opportunity to learn more about the BSC and to visit MareNostrum 5, a pre-exascale EuroHPC supercomputer hosted at BSC, as well as the Quantum computer.\n\nWe sincerely thank Dr. Debora Pina for her warm hospitality."
  },
  {
    "id": "reference-12",
    "date": "2026-06-24",
    "tag": "Publicação",
    "title": "Cooperação científica no INRIA Bordeaux",
    "text": "As part of our internationalization initiatives and the activities of the DECoHPC Équipe Associée, members of the UFFeScience Research Group had the opportunity to visit INRIA Bordeaux and meet with Dr. Luan Teylo, a researcher from the TADaaM Group.\n\nDuring the visit, Prof. Daniel de Oliveira and Wesley Ferreira, a Master's student at Universidade Federal Fluminense (UFF), discussed ongoing research on containerized workflow scheduling, particularly in the context of Wesley's Master's dissertation. \n\nThe meeting provided an excellent opportunity to exchange ideas, strengthen collaborations, and explore new research directions in scientific workflows across the computing continuum.\n\nThe visit also included two research presentations:\n\n🔹 Prof. Daniel de Oliveira presented:\n\n\"Federated Outlier Detection for LSST-Scale Astronomical Data in Clouds\"\n\nThe presentation discussed the challenges of applying Federated Learning to outlier detection in large-scale astronomical surveys, investigating performance, scalability, and cost trade-offs in distributed cloud environments.\n\n🔹 Wesley Ferreira presented:\n\n\"AkôFlow: A Container-based and Provenance-Aware Workflow Engine for Portable Execution Across the Computing Continuum\"\n\nThe talk introduced AkôFlow, an open-source workflow engine designed to support portable, provenance-aware, and resource-efficient execution of containerized workflows across heterogeneous environments, including HPC systems, clusters, and cloud infrastructures.\n\nWe thank the TADaaM Group and INRIA Bordeaux for the warm welcome and stimulating discussions. Initiatives such as this reinforce the importance of international scientific cooperation in advancing research and fostering innovation.\n\n#UFFeScience #Internationalization #ResearchCollaboration #ScientificWorkflows #HPC #FederatedLearning #INRIA #TADaaM #DECoHPC"
  },
  {
    "id": "reference-13",
    "date": "2026-06-15",
    "tag": "Publicação",
    "title": "ANCHOR: artigo aceito no SBBD 2026",
    "text": "🚀 New Paper Accepted at SBBD 2026! 🚀\n\nWe are happy to share that our latest research paper, \"Provenance-Guided Analysis of Agentic Workflows\" (Análise de Workflows Agênticos Guiada por Proveniência -- In Portuguese), has been accepted for presentation at the Brazilian Symposium on Databases (SBBD 2026)! 🇧🇷✨ \n\nThis work is a core part of Valesca Moura's M.Sc. dissertation at Instituto de Computação UFF under the supervision of Prof. Daniel de Oliveira (UFF) and Sandro Rama Fiorini (PUC-Behring Institute for Artificial Intelligence)\n\nAs Autonomous AI Agents and Large Language Models (LLMs) increasingly drive complex decision-making and automate workflows, a critical challenge emerges: How do we audit their choices and mitigate hallucinations when their reasoning remains hidden?\n \nThe proposed approach, ANCHOR (ANalysis of agentiC workflows via History and prOvenance), introduces a framework to solve this:\n\n🎛️ Telemetry & Interaction-Centric Capture: Tracing execution spans down to individual agent intentions and actions. \n\n📐 Data Structuring: Transforming unstructured logs into clear, hierarchical agent records (Interactions, Entities, Intentions). \n\n🌐 W3C PROV Alignment: Standardizing data to export rich, graph-based provenance models for thorough workflow auditing. \n\nFeel free to reach out at SBBD 2026 if you'd like to discuss agentic frameworks, data provenance, or AI auditability!\n\n#SBBD2026 #AIAgents #LLMs #DataProvenance #DataEngineering #ResponsibleAI #UFF #Research #MScDissertation"
  }
];
